#!/bin/bash

if [ -p /dev/stdin ]; then
    input=$(cat -)
elif [ $# -ne 0 ]; then
    input=$(echo $1)
else
    echo "パイプか引数を指定してください。"
    exit 1
fi

docker container exec ojtalk-ojtalk-1 trans :ja -b ${input} | tr -d '\n' && echo
